config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :periodo_feria
  resources :colaboradors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborador.rb
class Colaborador < ApplicationRecord
    has_many :periodos_ferias
    validates :nome, :cargo, :data_contratacao, presence: true
    validates :data_contratacao, date: { before_or_equal_to: Date.today }
    
    def dias_de_ferias
        agora = Time.now
        # calcula o tempo de trabalho em segundos
        tempo_trabalho = agora - self.data_contratacao.to_time
        # calcula o número de dias de férias a que tem direito
        dias_de_ferias = (tempo_trabalho / 1.year * 30).to_i
        # se o colaborador já tirou férias, subtrai os dias tirados do total
        dias_tirados = self.periodos_de_ferias.sum(:dias)
        dias_de_ferias - dias_tirados
      end
end
  

app/models/periodo_feria.rb
class PeriodoFerias < ApplicationRecord
  belongs_to :colaborador
  validates :data_inicio, :data_fim, presence: true
  validate :data_inicio_deve_ser_maior_ou_igual_a_12_meses_apos_contratacao
  validate :duracao_deve_ser_maior_ou_igual_a_10_dias
  validate :nao_deve_haver_sobreposicao_de_periodos
  validate :duracao_total_deve_ser_menor_ou_igual_a_30_dias_por_periodo

  private

  def data_inicio_deve_ser_maior_ou_igual_a_12_meses_apos_contratacao
    if colaborador && data_inicio.present? && data_inicio < colaborador.data_contratacao + 1.year
      errors.add(:data_inicio, "deve ser pelo menos 12 meses após a contratação")
    end
  end

  def duracao_deve_ser_maior_ou_igual_a_10_dias
    if data_inicio.present? && data_fim.present? && (data_fim - data_inicio).to_i < 10
      errors.add(:data_fim, "deve ser pelo menos 10 dias após a data de início")
    end
  end

  def nao_deve_haver_sobreposicao_de_periodos
    if colaborador && colaborador.periodos_ferias.where.not(id: id).any? { |p| (p.data_inicio..p.data_fim).overlaps?(data_inicio..data_fim) }
      errors.add(:data_inicio, "já existe um período de férias para este colaborador nesse intervalo")
    end
  end

  def duracao_total_deve_ser_menor_ou_igual_a_30_dias_por_periodo
    if colaborador && colaborador.periodos_ferias.where("data_inicio >= ?", data_inicio - 1.year).sum { |p| (p.data_fim - p.data_inicio).to_i } + (data_fim - data_inicio).to_i > 30
      errors.add(:data_inicio, "a duração total dos períodos de férias não pode ultrapassar 30 dias por período de 12 meses")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colaboradors_controller.rb
class ColaboradorsController < ApplicationController
  before_action :set_colaborador, only: %i[ show edit update destroy ]

  # GET /colaboradors or /colaboradors.json
  def index
    @colaboradors = Colaborador.all
  end

  # GET /colaboradors/1 or /colaboradors/1.json
  def show
  end

  # GET /colaboradors/new
  def new
    @colaborador = Colaborador.new
  end

  # GET /colaboradors/1/edit
  def edit
  end

  # POST /colaboradors or /colaboradors.json
  def create
    @colaborador = Colaborador.new(colaborador_params)

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to colaborador_url(@colaborador), notice: "Colaborador was successfully created." }
        format.json { render :show, status: :created, location: @colaborador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaboradors/1 or /colaboradors/1.json
  def update
    respond_to do |format|
      if @colaborador.update(colaborador_params)
        format.html { redirect_to colaborador_url(@colaborador), notice: "Colaborador was successfully updated." }
        format.json { render :show, status: :ok, location: @colaborador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradors/1 or /colaboradors/1.json
  def destroy
    @colaborador.destroy

    respond_to do |format|
      format.html { redirect_to colaboradors_url, notice: "Colaborador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborador
      @colaborador = Colaborador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def colaborador_params
      params.require(:colaborador).permit(:nome, :cargo, :data_contratacao)
    end
end

app/controllers/periodo_feria_controller.rb
class PeriodoFeriaController < ApplicationController
  before_action :set_periodo_ferium, only: %i[ show edit update destroy ]

  # GET /periodo_feria or /periodo_feria.json
  def index
    @periodos_de_ferias = PeriodoFerias.all
  end

  # GET /periodo_feria/1 or /periodo_feria/1.json
  def show
  end

  # GET /periodo_feria/new
  def new
    @periodos_de_ferias = PeriodoFerias.new
  end

  # GET /periodo_feria/1/edit
  def edit
  end

  # POST /periodo_feria or /periodo_feria.json
  def create
    @periodos_de_ferias= PeriodoFerias.new(periodo_ferias_params)

    respond_to do |format|
      if @periodo_ferias.save
        format.html { redirect_to periodo_ferium_url(@periodo_ferias), notice: "Periodo ferium was successfully created." }
        format.json { render :show, status: :created, location: @periodo_ferium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @periodo_ferias.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periodo_feria/1 or /periodo_feria/1.json
  def update
    respond_to do |format|
      if @periodo_ferias.update(periodo_ferium_params)
        format.html { redirect_to periodo_ferium_url(@periodo_ferias), notice: "Periodo ferium was successfully updated." }
        format.json { render :show, status: :ok, location: @periodo_ferias }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @periodo_ferias.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periodo_feria/1 or /periodo_feria/1.json
  def destroy
    @periodo_ferias.destroy

    respond_to do |format|
      format.html { redirect_to periodo_feria_url, notice: "Periodo ferias was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_periodo_ferias
      @periodo_ferias = PeriodoFerias.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def periodo_ferias_params
      params.require(:periodo_ferias).permit(:data_inicio, :data_fim, :colaborador_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colaboradors_helper.rb
module ColaboradorsHelper
end

app/helpers/periodo_feria_helper.rb
module PeriodoFeriaHelper
end

app/views/colaboradors/_colaborador.html.erb
<div id="<%= dom_id colaborador %>">
  <p>
    <strong>Nome:</strong>
    <%= colaborador.nome %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= colaborador.cargo %>
  </p>

  <p>
    <strong>Data contratacao:</strong>
    <%= colaborador.data_contratacao %>
  </p>

</div>

app/views/colaboradors/_form.html.erb
<%= form_with(model: colaborador) do |form| %>
  <% if colaborador.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
        <% colaborador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cargo, style: "display: block" %>
    <%= form.text_field :cargo %>
  </div>

  <div>
    <%= form.label :data_contratacao, style: "display: block" %>
    <%= form.date_field :data_contratacao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colaboradors/edit.html.erb
<h1>Editing colaborador</h1>

<%= render "form", colaborador: @colaborador %>

<br>

<div>
  <%= link_to "Show this colaborador", @colaborador %> |
  <%= link_to "Back to colaboradors", colaboradors_path %>
</div>

app/views/colaboradors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Colaboradors</h1>

<div id="colaboradors">
  <% @colaboradors.each do |colaborador| %>
    <%= render colaborador %>
    <p>
      <%= link_to "Show this colaborador", colaborador %>
    </p>
  <% end %>
</div>

<%= link_to "New colaborador", new_colaborador_path %>

app/views/colaboradors/new.html.erb
<h1>New colaborador</h1>

<%= render "form", colaborador: @colaborador %>

<br>

<div>
  <%= link_to "Back to colaboradors", colaboradors_path %>
</div>

app/views/colaboradors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @colaborador %>

<div>
  <%= link_to "Edit this colaborador", edit_colaborador_path(@colaborador) %> |
  <%= link_to "Back to colaboradors", colaboradors_path %>

  <%= button_to "Destroy this colaborador", @colaborador, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControleFerias</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/periodo_feria/_form.html.erb
<%= form_with(model: periodo_ferium) do |form| %>
  <% if periodo_ferium.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(periodo_ferium.errors.count, "error") %> prohibited this periodo_ferium from being saved:</h2>

      <ul>
        <% periodo_ferium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data_inicio, style: "display: block" %>
    <%= form.date_field :data_inicio %>
  </div>

  <div>
    <%= form.label :data_fim, style: "display: block" %>
    <%= form.date_field :data_fim %>
  </div>

  <div>
    <%= form.label :colaborador_id, style: "display: block" %>
    <%= form.text_field :colaborador_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/periodo_feria/_periodo_ferium.html.erb
<div id="<%= dom_id periodo_ferium %>">
  <p>
    <strong>Data inicio:</strong>
    <%= periodo_ferium.data_inicio %>
  </p>

  <p>
    <strong>Data fim:</strong>
    <%= periodo_ferium.data_fim %>
  </p>

  <p>
    <strong>Colaborador:</strong>
    <%= periodo_ferium.colaborador_id %>
  </p>

</div>

app/views/periodo_feria/edit.html.erb
<h1>Editing periodo ferium</h1>

<%= render "form", periodo_ferium: @periodo_ferium %>

<br>

<div>
  <%= link_to "Show this periodo ferium", @periodo_ferium %> |
  <%= link_to "Back to periodo feria", periodo_feria_path %>
</div>

app/views/periodo_feria/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Periodo feria</h1>

<div id="periodo_feria">
  <% @periodo_feria.each do |periodo_ferium| %>
    <%= render periodo_ferium %>
    <p>
      <%= link_to "Show this periodo ferium", periodo_ferium %>
    </p>
  <% end %>
</div>

<%= link_to "New periodo ferium", new_periodo_ferium_path %>

app/views/periodo_feria/new.html.erb
<h1>New periodo ferium</h1>

<%= render "form", periodo_ferium: @periodo_ferium %>

<br>

<div>
  <%= link_to "Back to periodo feria", periodo_feria_path %>
</div>

app/views/periodo_feria/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @periodo_ferium %>

<div>
  <%= link_to "Edit this periodo ferium", edit_periodo_ferium_path(@periodo_ferium) %> |
  <%= link_to "Back to periodo feria", periodo_feria_path %>

  <%= button_to "Destroy this periodo ferium", @periodo_ferium, method: :delete %>
</div>